apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: inception-deployment
spec:
  template:
    metadata:
      labels:
        app: inception-server
    spec:
      containers:
      - name: inception-container
        image: abhishek/inception
        imagePullPolicy: "IfNotPresent"
        command:
        - /bin/sh
        - -c
        args:
        - /root/tensorflow-serving/bazel-bin/tensorflow_serving/model_servers/tensorflow_model_server
          --port=9000 --use_saved_model=false --model_name=inception --model_base_path=/root/tensorflow-serving/inception-export
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: inception-service
  name: inception-service
spec:
  ports:
  - port: 9000
  selector:
    app: inception-server
  externalIPs: [192.168.122.66]
